apiVersion: v1
kind: Service
metadata:
  name: weatherappnew-service
  labels:
    app: weather-app-new
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: weather-app-new

